FROM python:3.10
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app
COPY ../producer_service /app
RUN pip install django kafka-python
EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]